services:
  server:
    image: ghcr.io/lukastrkan/pickup-point-widget:latest
    ports:
      - 8000:8000
    env_file:
      - .env
  supercluster:
    image: ghcr.io/lukastrkan/cluster-microservice:latest