# Generated by Django 5.0.1 on 2024-01-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('openning_hours', models.JSONField()),
                ('branch_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branchData.branchtype')),
            ],
        ),
    ]
