# Generated by Django 5.0.1 on 2024-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchData', '0002_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='branch',
            name='branchId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
