# Generated by Django 5.0.1 on 2024-02-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchData', '0003_alter_branch_options_branch_branchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
