# Generated by Django 5.0.1 on 2024-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchData', '0004_branchtype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/icons/'),
        ),
    ]
