# Generated by Django 5.0.1 on 2024-03-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchData', '0006_alter_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='box',
            field=models.BooleanField(default=False),
        ),
    ]
