# Generated by Django 5.0.1 on 2024-03-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchData', '0007_branch_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='wheelchair',
            field=models.BooleanField(default=False),
        ),
    ]
