# Generated by Django 5.0.1 on 2024-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchData', '0008_branch_card_branch_wheelchair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
