name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-widget-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Build and push widget (multi-arch)'
        run: |
          docker buildx create --use
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/lukastrkan/pickup-point-widget:latest \
            --push

  push-cluster-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Build and push cluster service (multi-arch)'
        working-directory: ./cluster-microservice
        run: |
          docker buildx create --use
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/lukastrkan/cluster-microservice:latest \
            --push
